#ifndef CONFIG_H
#define CONFIG_H

#define GRID_SIZE    5
#define CHAR_SIZE    4

#define CELL_SIZE   (GRID_SIZE*CHAR_SIZE)

#define BOARD_WIDTH  160
#define BOARD_HEIGHT 120

#define WINDOW_WIDTH  (BOARD_WIDTH * GRID_SIZE)
#define WINDOW_HEIGHT (BOARD_HEIGHT * GRID_SIZE)

#define TARGET_FPS   60

#endif
